### PR TITLE
feat: add new 'mini.nvim' highlight groups

### PR DESCRIPTION
**Pull request by echasnovski**
Add explicit support for all new groups since #33 and for the (hopefully) upcoming 'mini.icons'.

As was mentioned in the #33, I tried to link to existing "color" highlight groups as much as possible and did not use any bold attribute.

### CODE REVIEW

**Comment by bluz71** [comment]
Hello @echasnovski,

That is quite some work you have undertaken, involving some research into some of my existing helper highlights of this theme. Detailed & impressive. And you even remembered my weird _"no bold"_ attitude.

My only query pertains to:

```lua
highlight(0, "MiniFilesCursorLine", { link = "NightflyVisual" })
```

I already support NvimTree and NeoTree with these highlights:

```lua
highlight(0, "NvimTreeCursorLine", { bg = deep_blue })
highlight(0, "NeoTreeCursorLine", { bg = deep_blue })
```

I am inclined to change `MiniFilesCursorLine` to the same colors as `NvimTreeCursorLine` and `NeoTreeCursorLine`. If you object let me know.

Otherwise, merging.

Many thanks, and best regards.

**Comment by bluz71** [comment]
Sorry about that, re-opened and now merged.

**Comment by echasnovski** [comment]
> That is quite some work you have undertaken, involving some research into some of my existing helper highlights of this theme. Detailed & impressive. And you even remembered my weird _"no bold"_ attitude.

My pleasure. I respect any consistent design decisions. Plus the code has system, so it was that hard to stick to it.

> I am inclined to change `MiniFilesCursorLine` to the same colors as `NvimTreeCursorLine` and `NeoTreeCursorLine`. If you object let me know.

Sure, sounds reasonable. My only goal was to make current line in floating window visible. I'd then also suggest to use `NightflyCurrentLine` for `MiniPickMatchCurrent`, as it has the same usage (highlight current line in floating window). Both here and (similar highlight group) in 'vim-moonfly-colors'.

I'd also argue that visible in floating windows cursor line is the nice to have feature regardless of plugins. So maybe change `CursorLine` from `dark_blue` to `deep_blue`? Then there would be no need for `NightflyCurrentLine` group at all.

**Comment by bluz71** [comment]
> I'd also argue that visible in floating windows cursor line is the nice to have feature regardless of plugins. So maybe change `CursorLine` from `dark_blue` to `deep_blue`? Then there would be no need for `NightflyCurrentLine` group at all.

My memory is hazy at the moment, but I think I deliberately wanted a difference between "Filer" current line (NeoTree / MiniFiles) and `cursorline`, just as a want a difference between `QuickFix` current and `cursorline`.

I will fix `MiniPickMatchCurrent` now, good suggestion.

Best regards.

**Pull request merged**
